// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9l--OksAnNJYKNwFXWorNTvTIHlD2-gY',
    appId: '1:49632169054:web:10e50c3193e254510c38cf',
    messagingSenderId: '49632169054',
    projectId: 'vientrinotification',
    authDomain: 'vientrinotification.firebaseapp.com',
    storageBucket: 'vientrinotification.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCogUVy_IJuzKNdBT5VsvLf42IRBPYiMpo',
    appId: '1:49632169054:android:abf99f1bcb4e77250c38cf',
    messagingSenderId: '49632169054',
    projectId: 'vientrinotification',
    storageBucket: 'vientrinotification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk3SwGs6PkakyJklUTEXN-8SuXPnZaAUQ',
    appId: '1:49632169054:ios:eb96a0dde852ca650c38cf',
    messagingSenderId: '49632169054',
    projectId: 'vientrinotification',
    storageBucket: 'vientrinotification.firebasestorage.app',
    iosBundleId: 'com.example.vientri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk3SwGs6PkakyJklUTEXN-8SuXPnZaAUQ',
    appId: '1:49632169054:ios:eb96a0dde852ca650c38cf',
    messagingSenderId: '49632169054',
    projectId: 'vientrinotification',
    storageBucket: 'vientrinotification.firebasestorage.app',
    iosBundleId: 'com.example.vientri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9l--OksAnNJYKNwFXWorNTvTIHlD2-gY',
    appId: '1:49632169054:web:971602508df44dcd0c38cf',
    messagingSenderId: '49632169054',
    projectId: 'vientrinotification',
    authDomain: 'vientrinotification.firebaseapp.com',
    storageBucket: 'vientrinotification.firebasestorage.app',
  );
}
